---

- name: basic             # protector name - used in endpoint config block
  type: basic
  acls:
    - read:app
  credentials:
    - username: user1     # username
      password: "asdf"    # value (plain or hashed)
      hashed: "md5"       # optional: md5,sha1,sha256

- name: apikey            # protector name - used in endpoint config block
  type: http_header
  acls:
    - whatever
  headers:
    - name: x-apikey      # http header name to use
      hashed: "sha256"    # optional or md5,sha1,sha256
      value: "asdf"       # value (plain or hashed)

- name: ip
  type: ipaddress
  acls:
    - authed_by_network
  addresses:
    - 12.34.56.78/8

- name: bearer
  type: bearer
  # one of
  jwks_url: [issuer]/protocol/openid-connect/certs
  meta_url: [issuer]/.well-known/openid-configuration

#  keys_fetch_interval: 1h

#  token_accessor: ???

#  claims_validations:
#  - key: a.s.d
#    type: int | string | strs | ints
#    value: 123
#    length: 3
#    contains: "asd"
